// Starter content. Add more entries freely — the game picks at random.

export interface WordEntry {
  word: string;
  // A decoy that's adjacent to the word but is NEVER the word itself.
  imposterHint: string;
}

export const WORDS: WordEntry[] = [
  { word: "beach", imposterHint: "summer" },
  { word: "hospital", imposterHint: "doctor" },
  { word: "wedding", imposterHint: "party" },
  { word: "airport", imposterHint: "vacation" },
  { word: "gym", imposterHint: "healthy" },
  { word: "library", imposterHint: "quiet" },
  { word: "school", imposterHint: "homework" },
  { word: "restaurant", imposterHint: "dinner" },
  { word: "zoo", imposterHint: "animals" },
  { word: "cinema", imposterHint: "popcorn" },
  { word: "supermarket", imposterHint: "groceries" },
  { word: "park", imposterHint: "outdoors" },
  { word: "office", imposterHint: "meeting" },
  { word: "kitchen", imposterHint: "cooking" },
  { word: "bedroom", imposterHint: "sleep" },
  { word: "bathroom", imposterHint: "shower" },
  { word: "garden", imposterHint: "plants" },
  { word: "farm", imposterHint: "tractor" },
  { word: "mountain", imposterHint: "hiking" },
  { word: "desert", imposterHint: "hot" },
  { word: "forest", imposterHint: "trees" },
  { word: "ocean", imposterHint: "waves" },
  { word: "snow", imposterHint: "winter" },
  { word: "rain", imposterHint: "umbrella" },
  { word: "birthday", imposterHint: "cake" },
  { word: "concert", imposterHint: "music" },
  { word: "museum", imposterHint: "history" },
  { word: "casino", imposterHint: "gambling" },
  { word: "bank", imposterHint: "money" },
  { word: "pharmacy", imposterHint: "medicine" },
  { word: "dentist", imposterHint: "teeth" },
  { word: "barber", imposterHint: "haircut" },
  { word: "bakery", imposterHint: "bread" },
  { word: "stadium", imposterHint: "sports" },
  { word: "pool", imposterHint: "swimming" },
  { word: "campsite", imposterHint: "tent" },
  { word: "spaceship", imposterHint: "astronaut" },
  { word: "castle", imposterHint: "king" },
  { word: "pirate ship", imposterHint: "treasure" },
  { word: "haunted house", imposterHint: "ghost" },
  { word: "circus", imposterHint: "clown" },
  { word: "volcano", imposterHint: "lava" },
  { word: "coffee shop", imposterHint: "espresso" },
  { word: "fire station", imposterHint: "firefighter" },
  { word: "police station", imposterHint: "officer" },
  { word: "courtroom", imposterHint: "judge" },
  { word: "prison", imposterHint: "cell" },
  { word: "church", imposterHint: "prayer" },
  { word: "temple", imposterHint: "monk" },
  { word: "graveyard", imposterHint: "tombstone" },
  { word: "aquarium", imposterHint: "fish" },
  { word: "theme park", imposterHint: "rollercoaster" },
  { word: "bowling alley", imposterHint: "strike" },
  { word: "arcade", imposterHint: "tokens" },
  { word: "nightclub", imposterHint: "dancing" },
  { word: "cocktail bar", imposterHint: "olives" },
  { word: "theater", imposterHint: "stage" },
  { word: "opera", imposterHint: "soprano" },
  { word: "ballet", imposterHint: "tutu" },
  { word: "art gallery", imposterHint: "painting" },
  { word: "bookstore", imposterHint: "novel" },
  { word: "toy store", imposterHint: "dolls" },
  { word: "pet shop", imposterHint: "puppy" },
  { word: "flower shop", imposterHint: "bouquet" },
  { word: "butcher", imposterHint: "meat" },
  { word: "laundromat", imposterHint: "washing" },
  { word: "car wash", imposterHint: "soap" },
  { word: "gas station", imposterHint: "fuel" },
  { word: "subway", imposterHint: "underground" },
  { word: "train station", imposterHint: "platform" },
  { word: "harbor", imposterHint: "boats" },
  { word: "lighthouse", imposterHint: "beacon" },
  { word: "factory", imposterHint: "assembly" },
  { word: "warehouse", imposterHint: "storage" },
  { word: "construction site", imposterHint: "crane" },
  { word: "mine", imposterHint: "coal" },
  { word: "oil rig", imposterHint: "drilling" },
  { word: "windmill", imposterHint: "breeze" },
  { word: "dam", imposterHint: "reservoir" },
  { word: "bridge", imposterHint: "crossing" },
  { word: "tunnel", imposterHint: "dark" },
  { word: "skyscraper", imposterHint: "elevator" },
  { word: "mansion", imposterHint: "luxury" },
  { word: "cottage", imposterHint: "cozy" },
  { word: "cabin", imposterHint: "fireplace" },
  { word: "igloo", imposterHint: "ice" },
  { word: "treehouse", imposterHint: "branches" },
  { word: "barn", imposterHint: "hay" },
  { word: "greenhouse", imposterHint: "humid" },
  { word: "orchard", imposterHint: "apples" },
  { word: "vineyard", imposterHint: "grapes" },
  { word: "ranch", imposterHint: "cattle" },
  { word: "jungle", imposterHint: "vines" },
  { word: "swamp", imposterHint: "mud" },
  { word: "cave", imposterHint: "bats" },
  { word: "cliff", imposterHint: "edge" },
  { word: "waterfall", imposterHint: "cascade" },
  { word: "island", imposterHint: "tropical" },
  { word: "glacier", imposterHint: "frozen" },
  { word: "canyon", imposterHint: "gorge" },
  { word: "meadow", imposterHint: "wildflowers" },
  { word: "river", imposterHint: "current" },
  { word: "lake", imposterHint: "calm" },
  { word: "pond", imposterHint: "ducks" },
  { word: "reef", imposterHint: "coral" },
  { word: "savanna", imposterHint: "lions" },
  { word: "rainforest", imposterHint: "canopy" },
  { word: "moon", imposterHint: "crater" },
  { word: "galaxy", imposterHint: "stars" },
  { word: "comet", imposterHint: "tail" },
  { word: "observatory", imposterHint: "telescope" },
  { word: "laboratory", imposterHint: "experiment" },
  { word: "classroom", imposterHint: "chalkboard" },
  { word: "dormitory", imposterHint: "roommate" },
  { word: "cafeteria", imposterHint: "tray" },
  { word: "playground", imposterHint: "swings" },
  { word: "fairground", imposterHint: "carousel" },
  { word: "carnival", imposterHint: "mask" },
  { word: "parade", imposterHint: "floats" },
  { word: "festival", imposterHint: "crowd" },
  { word: "farmers market", imposterHint: "produce" },
  { word: "mall", imposterHint: "shopping" },
  { word: "boutique", imposterHint: "fashion" },
  { word: "jewelry store", imposterHint: "diamonds" },
  { word: "hardware store", imposterHint: "tools" },
  { word: "clinic", imposterHint: "nurse" },
  { word: "spa", imposterHint: "massage" },
  { word: "sauna", imposterHint: "steam" },
  { word: "ski resort", imposterHint: "slopes" },
  { word: "ice rink", imposterHint: "skating" },
  { word: "golf course", imposterHint: "putting" },
  { word: "tennis court", imposterHint: "racket" },
  { word: "basketball court", imposterHint: "hoop" },
  { word: "soccer field", imposterHint: "goal" },
  { word: "boxing ring", imposterHint: "gloves" },
  { word: "racetrack", imposterHint: "speed" },
  { word: "stable", imposterHint: "horses" },
  { word: "safari", imposterHint: "wildlife" },
  { word: "oasis", imposterHint: "palm" },
  { word: "lemonade stand", imposterHint: "lemons" },
  { word: "food truck", imposterHint: "tacos" },
  { word: "rooftop", imposterHint: "skyline" },
  { word: "pizza", imposterHint: "pepperoni" },
  { word: "sushi", imposterHint: "wasabi" },
  { word: "hamburger", imposterHint: "patty" },
  { word: "ice cream", imposterHint: "scoop" },
  { word: "popcorn", imposterHint: "butter" },
  { word: "pancakes", imposterHint: "syrup" },
  { word: "spaghetti", imposterHint: "noodles" },
  { word: "taco", imposterHint: "shell" },
  { word: "doughnut", imposterHint: "glaze" },
  { word: "sandwich", imposterHint: "lunch" },
  { word: "barbecue", imposterHint: "grill" },
  { word: "chocolate", imposterHint: "cocoa" },
  { word: "cheese", imposterHint: "dairy" },
  { word: "coffee", imposterHint: "caffeine" },
  { word: "tea", imposterHint: "kettle" },
  { word: "smoothie", imposterHint: "blender" },
  { word: "cereal", imposterHint: "breakfast" },
  { word: "soup", imposterHint: "spoon" },
  { word: "salad", imposterHint: "lettuce" },
  { word: "cake", imposterHint: "frosting" },
  { word: "bicycle", imposterHint: "pedals" },
  { word: "motorcycle", imposterHint: "helmet" },
  { word: "helicopter", imposterHint: "rotor" },
  { word: "submarine", imposterHint: "periscope" },
  { word: "hot air balloon", imposterHint: "basket" },
  { word: "sailboat", imposterHint: "mast" },
  { word: "tractor", imposterHint: "plow" },
  { word: "ambulance", imposterHint: "siren" },
  { word: "fire truck", imposterHint: "ladder" },
  { word: "rocket", imposterHint: "launch" },
  { word: "taxi", imposterHint: "fare" },
  { word: "limousine", imposterHint: "chauffeur" },
  { word: "skateboard", imposterHint: "ramp" },
  { word: "canoe", imposterHint: "paddle" },
  { word: "jet ski", imposterHint: "spray" },
  { word: "umbrella", imposterHint: "drizzle" },
  { word: "mirror", imposterHint: "reflection" },
  { word: "clock", imposterHint: "ticking" },
  { word: "lamp", imposterHint: "bulb" },
  { word: "pillow", imposterHint: "nap" },
  { word: "blanket", imposterHint: "warm" },
  { word: "candle", imposterHint: "wick" },
  { word: "binoculars", imposterHint: "zoom" },
  { word: "backpack", imposterHint: "straps" },
  { word: "suitcase", imposterHint: "packing" },
  { word: "wallet", imposterHint: "cash" },
  { word: "toothbrush", imposterHint: "bristles" },
  { word: "hairdryer", imposterHint: "blowing" },
  { word: "vacuum", imposterHint: "dust" },
  { word: "broom", imposterHint: "sweeping" },
  { word: "rainbow", imposterHint: "colorful" },
  { word: "thunderstorm", imposterHint: "lightning" },
  { word: "tornado", imposterHint: "funnel" },
  { word: "hurricane", imposterHint: "wind" },
  { word: "earthquake", imposterHint: "tremor" },
  { word: "avalanche", imposterHint: "slide" },
  { word: "sunset", imposterHint: "dusk" },
  { word: "sunrise", imposterHint: "dawn" },
  { word: "fog", imposterHint: "misty" },
  { word: "hail", imposterHint: "pellets" },
  { word: "dolphin", imposterHint: "flippers" },
  { word: "penguin", imposterHint: "waddle" },
  { word: "elephant", imposterHint: "trunk" },
  { word: "giraffe", imposterHint: "tall" },
  { word: "kangaroo", imposterHint: "pouch" },
  { word: "octopus", imposterHint: "tentacles" },
  { word: "butterfly", imposterHint: "wings" },
  { word: "spider", imposterHint: "web" },
  { word: "owl", imposterHint: "nocturnal" },
  { word: "shark", imposterHint: "fin" },
  { word: "marathon", imposterHint: "running" },
  { word: "surfing", imposterHint: "board" },
  { word: "skiing", imposterHint: "poles" },
  { word: "fishing", imposterHint: "bait" },
  { word: "hiking", imposterHint: "trail" },
  { word: "yoga", imposterHint: "stretching" },
  { word: "chess", imposterHint: "checkmate" },
  { word: "poker", imposterHint: "bluff" },
  { word: "darts", imposterHint: "bullseye" },
  { word: "karaoke", imposterHint: "microphone" },
  { word: "halloween", imposterHint: "costume" },
  { word: "christmas", imposterHint: "sleigh" },
  { word: "thanksgiving", imposterHint: "turkey" },
  { word: "easter", imposterHint: "eggs" },
  { word: "new year", imposterHint: "fireworks" },
  { word: "graduation", imposterHint: "diploma" },
  { word: "prom", imposterHint: "dance" },
  { word: "funeral", imposterHint: "mourning" },
  { word: "baby shower", imposterHint: "gifts" },
  { word: "reunion", imposterHint: "gathering" },
  { word: "firefighter", imposterHint: "hose" },
  { word: "astronaut", imposterHint: "spacesuit" },
  { word: "chef", imposterHint: "recipe" },
  { word: "pilot", imposterHint: "cockpit" },
  { word: "magician", imposterHint: "trick" },
  { word: "detective", imposterHint: "clues" },
  { word: "scientist", imposterHint: "formula" },
  { word: "painter", imposterHint: "canvas" },
  { word: "musician", imposterHint: "band" },
  { word: "photographer", imposterHint: "camera" },
];

export const NUMBER_CATEGORIES: string[] = [
  "How good is this experience? (0–10)",
  "How awkward is this situation? (0–10)",
  "How stressful is this? (0–10)",
  "How good a first-date idea is this? (0–10)",
  "How nostalgic is this? (0–10)",
  "How scary is this? (0–10)",
  "How overrated is this? (0–10)",
  "How embarrassing is this? (0–10)",
  "How relaxing is this? (0–10)",
  "How expensive is this? (0–10)",
  "How healthy is this? (0–10)",
  "How likely would you do this again? (0–10)",
  "How weird is this? (0–10)",
  "How dangerous is this? (0–10)",
  "How exciting is this? (0–10)",
  "How annoying is this? (0–10)",
];

export function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
